oxc_image: xcode8
language: objective-c
xcode-project: CRTimePicker.xcworkspace
xcode_scheme: CRTimePicker
xcode_sdk: iphonesimulator8.4
script:
    - xcodebuild -scheme 'CRTimePicker-iOS' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty -c
    - xcodebuild -scheme 'CRTimePicker-OSX' test | xcpretty -c